# docker-compose up -d
version: '3'
services:
  db:
    env_file:
      - .env
    image: mysql
    container_name: nethelper_mysql
    networks:
      nethelper-network:
        ipv4_address: 172.1.0.2
    volumes:
      # 路径需要根据服务器具体情况修改
      - ./data/db:/var/lib/mysql
      # 将容器中运行的mysql数据保存到宿主机，防止容器删除后数据丢失
      - ./service/mysql/mysql.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      #数据库初始话为root用户设置的默认密码
      MYSQL_DATABASE: nethelper
      #数据库名
      MYSQL_USER: nethelper
      #自定义数据库的用户，权限只作用于MYSQL_DATABASE配置的数据库
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      #自定义数据库的用户，权限只作用于MYSQL_DATABASE配置的数据库
  web:
    image: nginx
    container_name: nethelper_nginx
    restart: always
    networks:
      nethelper-network:
        ipv4_address: 172.1.0.3
    ports:
      - 443:443
      - 80:80
      - 3000:3000
    volumes:
      - ./service/nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./service/nginx/logs:/var/log/nginx
      - /etc/ssl/certs:/etc/ssl/certs
      - /etc/ssl/private:/etc/ssl/private
  koa:
    image: sztunethelper:0.0.2
    container_name: nethelper_koa
    networks:
      nethelper-network:
        ipv4_address: 172.1.0.4
    ports:
      - 8000:3000
      - 8001:3001
    volumes:
      - ./log:/usr/sztunethelper-center/log
      - .env:/usr/sztunethelper-center/.env
networks:
  nethelper-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.1.0.0/16
  